# Generated by Django 2.0.5 on 2018-06-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180604_1659'),
        ('orders', '0005_productinbascet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInBascet',
            new_name='ProductInBasket',
        ),
    ]
